build: fix standalone release checks failing due to missing global `ReleaseAction` instance
Fixes the standalone release checks running outside of the `.ng-dev` config load, which
comes with the `global.ReleaseAction`. In standalone checks this variable is not
defined and therefore currently causes errors like:

```
/.ng-dev/release.ts:14
const actionProto = (global as any).ReleaseAction.prototype;
                                                  ^
TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.<anonymous>
```

We can fallback to the imported `ReleaseAction` constructor object if the global reference
is not provided. In such cases the monkey-patching is a noop anyway.